### ISSUE TITLE
Error during startup ( No module named 'braviapsk')

### ISSUE THREAD

**Issue by antimix** [custom-components/media_player.braviatv_psk#11]
Hello, I am running Home Assistant (hassio) 0.92.2.
I have a Sony Bravia Android TV KD-55x8507C.

I created the following folder structure:
     custom_components\braviatv_psk
under the configuration folder, and I copied inside the two files:
     media_player.py
     __init__.py

I configured the Sony with preshared key following the instructions.

I added the following text to configuration.yaml
media_player:
  - platform: braviatv_psk
    host: 10.20.1.124
    psk: '2931'
    amp: True
    android: True
    name: SONY_BRAVIA

then I restarted HA.

The Sony did not appeared as a mediaplayer entity.
Looking at the HA log I found the following:

Log Details (ERROR)

Sat May 04 2019 16:37:10 GMT+0200 (ora solare Europa occidentale)

Error while setting up platform braviatv_psk

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/homeassistant/helpers/entity_platform.py", line 126, in _async_setup_platform
    SLOW_SETUP_MAX_WAIT, loop=hass.loop)
  File "/usr/local/lib/python3.7/asyncio/tasks.py", line 416, in wait_for
    return fut.result()
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/braviatv_psk/media_player.py", line 90, in setup_platform
    [BraviaTVDevice(host, psk, mac, name, amp, android, source_filter)])
  File "/config/custom_components/braviatv_psk/media_player.py", line 99, in __init__
    from braviapsk import sony_bravia_psk
ModuleNotFoundError: No module named 'braviapsk'

Any idea of what is the issue ?

Regards

**Comment by gerard33** [comment]
Just do another restart. The package is not yet fully installed when HA tried to open it. A restart will fix that.

**Comment by gerard33** [comment]
See also the last paragraph of the readme ;-)

**Comment by antimix** [comment]
Rebooted.  Still does not work.
Same error in log :(

**Comment by gerard33** [comment]
Rebooted? Or restarted HA?

**Comment by antimix** [comment]
from web UI. Configuration, General, (server management) RESTART...
do it makes difference ?

**Comment by gerard33** [comment]
Yeah a reboot is something else than a restart.

You are doing it the correct way. Just reboot again in a few minutes. It should work.

**Comment by antimix** [comment]
Just some tricky additional info.
The Sony device is known by HA, that has it already inside his device registry. Here is the portion of the data:
----
            {
                "area_id": "e562d9f5556d490390e46383c6dee14b",
                "config_entries": [
                    "b0d84170fe2a43d4ad696352337622b7"
                ],
                "connections": [],
                "hub_device_id": null,
                "id": "cb02bcb46db0447295b7bbc83ff06d17",
                "identifiers": [
                    [
                        "cast",
                        "fcd93713ad370ce1a069746b1f967970"
                    ]
                ],
                "manufacturer": "Sony",
                "model": "BRAVIA 4K 2015",
                "name": "KD-55X8507C",
                "name_by_user": null,
                "sw_version": null
            },
----
and the TV is actually seen only as his GoogleCast (SonyCast) functional device. So in HA it is present as a GoogleCast multimedia entity but not as a multimedia TV (normally I expect to have both two)
here is the actual entry for the GoogleCast entity from the registry entity:
---
            {
                "config_entry_id": "b0d84170fe2a43d4ad696352337622b7",
                "device_id": "cb02bcb46db0447295b7bbc83ff06d17",
                "disabled_by": null,
                "entity_id": "media_player.kd_55x8507c",
                "name": null,
                "platform": "cast",
                "unique_id": "fcd93713-ad37-0ce1-a069-746b1f967970"
            },
--
So after your plugin installation I would expected to have the Sony TV to appear as multimedia entity.
But nothing changes. I have still only the GoogleCast (SonyCast) device for the Android part.

**Comment by antimix** [comment]
Sorry for the screwed up fonts...

**Comment by djinn5150** [comment]
I am having the same results as OP although my tv is not showing in the registry.  Original bravia component works, was looking for a little more control options and found myself here after having no go with androidtv component.

**Comment by antimix** [comment]
**I was able to solve the issue.** Now I have the Sony as TV in a mediaplayer  entity.
Let me explain how I have done, since there are tons of issues like this in various forum.

1) I want to clarify that Home Assistant is not HASS.IO, or at least the two installations are not 100% code equivalent. This means that they can have slide different code versions and packages versions. As example one can be less updated then the other but more stable on a particular version. 
2) Components written by the community may not be "aligned" on the last code version, that means that recent breaking changes may fail the component on a last updated HA installation. On the contrary on a less recent HA installation a component updated for a latest version of HA can stop to work or not work at all.
3) Even if the component code has not been changed, a new version of HA can have different version of the python packages installed, that means code incompatibility.
4) Even if no new version have been deployed, HA and HASSIO may not have the same python packages installed from a version to another.
5) In HASSIO is not normally possible to play around with command line, do "pip import" or make any sort of library add or system change. Is an almost an "out of the box" packaged system, that 99% does not require skill to be setup, easy to use for unskilled users, and should be taken as it is. Any issue should be automatically resolved by a following "next release" of the system or component.

Said that, **I have HASSIO**. 
After some hours I realized that the custom component **"braviatv_psk"** uses a python library called **"braviapsk"** that is present in HA but not in HASSIO. 
From this library the component uses **"sony_bravia_psk"**, so just adding this python library solved the issue.
I looked at the ERROR LOG above, and saw what the missing module was: 
-> "_No module named_ **'braviapsk'"**

So I went on [Github Home Assistant repository](https://github.com/home-assistant/home-assistant/tree/dev/homeassistant) and downloaded it. Then I extracted the **'braviapsk'** module (is a folder) to be added on my HASS.IO installation.

Now that I got it, it was time to add it to HASS.IO

### HOW TO ADD CUSTOM LIBRARIES USED BY A COMPONENT

1) Go under  your **custom_component** folder under the config folder
2) Simply unzip there the folder
in my case on the **'custom_component'** folder I had:
**bravia_psk**  _<-- the custom component_
**braviapsk** _<-- the library_ 
3) Then modify the code of the custom component to load the library from there:
e.g.
----------------------- This is **media_player.py** under the bravia_psk folder -------------------
...
class BraviaTVDevice(MediaPlayerDevice):
    """Representation of a Sony Bravia TV."""

    def __init__(self, host, psk, mac, name, amp, android, source_filter):
        """Initialize the Sony Bravia device."""
        _LOGGER.info("Setting up Sony Bravia TV")
        from **custom_components.braviapsk** import sony_bravia_psk **as sony_bravia_psk**

....
---------------------------------------------------------------------------------------------------------
Save all, verify the HASSIO configuration, and restart.
It worked like a charm.

**Comment by gerard33** [comment]
Good that it works for you after the changes :+1: 

Your explanation on Home Assistant vs hass.io and the way the packages work is not correct however.
First of all I am using hass.io myself and the component is working fine for me and a lot of other people using hass.io.
Here is some more explanation on Home Assistant vs hass.io -> https://www.home-assistant.io/faq/ha-vs-hassio.

The package `braviapsk` is the one I have made, and its definitely not available by default in Home Assistant (and that way also not in hass.io). The package is available on PyPi and on [Github](https://github.com/gerard33/sony_bravia_psk), but not on the HA github.
That's the way all components work by the way, they install the package on demand on your local install -> https://developers.home-assistant.io/docs/en/creating_integration_manifest.html#requirements.

Check your `config\deps\lib\python3.7\site-packages` folder. There should be a folder `braviapsk` and `pySonyBraviaPSK-0.1.7.dist-info` in there.

> After some hours I realized that the custom component "braviatv_psk" uses a python library called "braviapsk" that is present in HA but not in HASSIO.

So that's not correct.

> I looked at the ERROR LOG above, and saw what the missing module was:
-> "No module named 'braviapsk'"

That's the reason I asked you to restart HA. I have had this myself sometimes as well were the package is not yet installed while HA already tries to use it.
That's also why this text is in the readme
`Due to how custom_components are loaded, it is normal to see a ModuleNotFoundError error on first boot after adding this, to resolve it, restart Home-Assistant.`

**Comment by gerard33** [comment]
@djinn5150 

> Original bravia component works, was looking for a little more control options and found myself here after having no go with androidtv component.

I have read on the forum that another user had fixed the issues when he removed the original `bravia` component from his config. Can you try that?

**Comment by antimix** [comment]
Hi Gerard, let me understand better. 

You are right. I looked today at my HASSIO and I found a new folder:
**config\deps\lib\python3.6\site-packages**
it was not present a couple of days ago.

and guess... inside there are two other folders:
**pySonyBraviaPSK-0.1.7.dist-info
braviapsk**

so I should assume that an internal process of HASSIO downloaded the missing libraries several minutes after my restarts, and probably they terminated the download after I already created the patched version.
I can say that braviapsk is exactly the same file I put in my folder.

If this is correct, the easy solution would have been to **_"don't be in a hurry"_**, and simply wait until HASSIO would have completed the download. I will correct my post, since I would like to give correct info to the users.
I will also try to delete my braviapsk folder and revert the media_player.py to its original version, and it should be able to use the braviapsk in config\deps\lib\python3.6\site-packages.

Regards

**Comment by gerard33** [comment]
@antimix, @djinn5150,
Can you please check this forum post -> https://community.home-assistant.io/t/sony-bravia-tv-component-with-pre-shared-key/30698/341?u=gerard33.

Looks like the file `manifest.json` is not optional for custom components although that was in the HA release notes.

So it looks like that was the reason the package didn't install on your new HA install.

I have added that file here, can you add it to your config and see if it works now.

**Comment by gerard33** [comment]
@antimix you will probably not notice a difference since you already installed the package manually. But nevertheless it should be fixed right now.

**Comment by vinodnx** [comment]
> **I was able to solve the issue.** Now I have the Sony as TV in a mediaplayer entity.
> Let me explain how I have done, since there are tons of issues like this in various forum.
> 
> 1. I want to clarify that Home Assistant is not HASS.IO, or at least the two installations are not 100% code equivalent. This means that they can have slide different code versions and packages versions. As example one can be less updated then the other but more stable on a particular version.
> 2. Components written by the community may not be "aligned" on the last code version, that means that recent breaking changes may fail the component on a last updated HA installation. On the contrary on a less recent HA installation a component updated for a latest version of HA can stop to work or not work at all.
> 3. Even if the component code has not been changed, a new version of HA can have different version of the python packages installed, that means code incompatibility.
> 4. Even if no new version have been deployed, HA and HASSIO may not have the same python packages installed from a version to another.
> 5. In HASSIO is not normally possible to play around with command line, do "pip import" or make any sort of library add or system change. Is an almost an "out of the box" packaged system, that 99% does not require skill to be setup, easy to use for unskilled users, and should be taken as it is. Any issue should be automatically resolved by a following "next release" of the system or component.
> 
> Said that, **I have HASSIO**.
> After some hours I realized that the custom component **"braviatv_psk"** uses a python library called **"braviapsk"** that is present in HA but not in HASSIO.
> From this library the component uses **"sony_bravia_psk"**, so just adding this python library solved the issue.
> I looked at the ERROR LOG above, and saw what the missing module was:
> -> "_No module named_ **'braviapsk'"**
> 
> So I went on [Github Home Assistant repository](https://github.com/home-assistant/home-assistant/tree/dev/homeassistant) and downloaded it. Then I extracted the **'braviapsk'** module (is a folder) to be added on my HASS.IO installation.
> 
> Now that I got it, it was time to add it to HASS.IO
> 
> ### HOW TO ADD CUSTOM LIBRARIES USED BY A COMPONENT
> 1. Go under  your **custom_component** folder under the config folder
> 2. Simply unzip there the folder
>    in my case on the **'custom_component'** folder I had:
>    **bravia_psk**  _<-- the custom component_
>    **braviapsk** _<-- the library_
> 3. Then modify the code of the custom component to load the library from there:
>    e.g.
>    ----------------------- This is **media_player.py** under the bravia_psk folder -------------------
>    ...
>    class BraviaTVDevice(MediaPlayerDevice):
>    """Representation of a Sony Bravia TV."""
>    def **init**(self, host, psk, mac, name, amp, android, source_filter):
>    """Initialize the Sony Bravia device."""
>    _LOGGER.info("Setting up Sony Bravia TV")
>    from **custom_components.braviapsk** import sony_bravia_psk **as sony_bravia_psk**
> 
> ## ....
> Save all, verify the HASSIO configuration, and restart.
> It worked like a charm.

Hello Expert.
Please help me I am struggling more than two days to config my sony android tv. noting is showing in my home assistant. i am doing as per your instruction.
As i am new i hope i am doing some mistake in this point

No-1
>    **bravia_psk**  _<-- the custom component_
>    **braviapsk** _<-- the library_ ( where is this librany )

No-2

(do I need to copy all this ?
>    ...
>    class BraviaTVDevice(MediaPlayerDevice):
>    """Representation of a Sony Bravia TV."""
>    def **init**(self, host, psk, mac, name, amp, android, source_filter):
>    """Initialize the Sony Bravia device."""
>    _LOGGER.info("Setting up Sony Bravia TV")
>    from **custom_components.braviapsk** import sony_bravia_psk **as sony_bravia_psk**

Please support
![Capture](https://user-images.githubusercontent.com/60498153/79538721-e3752400-8052-11ea-9c31-a280628076d1.JPG)

**Comment by gerard33** [comment]
@vinodnx Don’t follow that procedure as that is not correct.
First delete your bravia folder as it contains files that should not be there.
Then install the component via HACS.
If you face any issues please open a new issue with all the detaila so we can try to help you.
