### ISSUE TITLE
Request: Add alias to source

### ISSUE THREAD

**Issue by jimbob1001** [custom-components/media_player.braviatv_psk#15]
Hi, just wondered if it would be at all possible to add an alias to an HDMI source. ....

```
 - platform: braviatv_psk
   name: "Sony Bravia"
   host: ip_address
   psk: sony_psk
   mac: mac_address
   amp: 'true'
   android: 'true'
   sourcefilter:
     - "HDMI 1": "TV"
     - "HDMI 2": "CHROMECAST"
     - "HDMI 3": "SHIELD"
     - "HDMI 4": "PC"
```
Or would there be some other way of displaying a friendly list of hdmi sources - I can never remember which source is which when the options are just HDMI 1, 2, 3 or 4, and always choose the wrong one!

Cheers,
James

**Comment by gerard33** [comment]
Adding an alias is not possible as the sourcefilter is used for actually sorting the list.
But you can use [input_select](https://www.home-assistant.io/components/input_select/) to achieve that.
