### ISSUE TITLE
Component not working despite valid configuration

### ISSUE THREAD

**Issue by ionothanus** [custom-components/media_player.braviatv_psk#16]
I have an XBR-65X850E connected by LAN, which I can't seem to get working properly with this component. The component will turn on my TV from standby, but won't do anything else. I've installed the component through HACS on Home Assistant v0.98.2. I've set up the configuration as follows:

    media_player:
      - platform: braviatv_psk
        name: bravia-tv
        host: 10.0.0.80
        psk: sony
        mac: 70:26:05:XX:XX:XX
        amp: True

I've confirmed the PSK is correct. All I get is the following log error repeated:

`Timeout occurred: HTTPConnectionPool(host='10.0.0.80', port=80): Read timed out. (read timeout=8)`

I can ping my TV at its IP (which is static) and I can interact with it using [these scripts](https://github.com/breunigs/bravia-auth-and-remote). It works with the built-in PIN-based component. I removed that component from my configuration before adding this one.

**Comment by gerard33** [comment]
Can you enable debugging in the log for the component?
What does this line show then in the log `Set up Sony Bravia TV with IP: ...`?

**Comment by ionothanus** [comment]
Here's all the useful log output:

    2019-09-02 18:33:43 INFO (SyncWorker_1) [custom_components.braviatv_psk.media_player] Setting up Sony Bravia TV
    2019-09-02 18:33:43 DEBUG (SyncWorker_1) [custom_components.braviatv_psk.media_player] Set up Sony Bravia TV with IP: 10.0.0.80, PSK: sony, MAC: 70:26:05:XX:XX:XX
    2019-09-02 18:33:51 ERROR (SyncWorker_1) [braviapsk.sony_bravia_psk] Timeout occurred: HTTPConnectionPool(host='10.0.0.80', port=80): Read timed out. (read timeout=8)
    2019-09-02 18:33:51 DEBUG (SyncWorker_1) [custom_components.braviatv_psk.media_player] No data received from TV. Error message: 'NoneType' object has no attribute 'get'

**Comment by gerard33** [comment]
Hmm, that's strange. The set up with the TV seems to be correctly made.
Can you try to change the PSK on the TV and in the config.yaml? Because based on the error message the HA can't get a connection with the TV.

**Comment by ionothanus** [comment]
I had tried several PSKs before settling on "sony".

FYI, if I try a few times, powering off the TV from HA also works.

Are there any other debugging steps I can try?

**Comment by jasonchrin** [comment]
Were you ever able to figure this out?  I'm in the same situation now.  I'm using a wifi connection on my TV if that makes a difference.

**Comment by ionothanus** [comment]
Nah, I gave up and went back to the broken built-in one. Would still love to make this work though. 

To your point about wifi - my TV is hardwired. Is yours the same model as mine (see first post)?

**Comment by jasonchrin** [comment]
Mine is the previous generation, 43x800d

**Comment by gerard33** [comment]
Closing this issue as it's a few months old. Feel free to open a new issue if still applicable.
