### ISSUE TITLE
[question] How is it different from standard BraviaTV integration?

### ISSUE THREAD

**Issue by PawelTroka** [custom-components/media_player.braviatv_psk#23]
Is it better or different (and if so then in what regard) than Home Assistant official integration for BraviaTV (https://www.home-assistant.io/integrations/braviatv/) ?

**Comment by gerard33** [comment]
More info here -> https://community.home-assistant.io/t/sony-bravia-tv-component-with-pre-shared-key/30698?u=gerard33

Just give it a try and you can see for yourself :smile:

**Comment by PawelTroka** [comment]
So basically it's just better BraviaTV integration. Why not merge to Home Assistant Core then?

**Comment by gerard33** [comment]
Not saying it's better, but for me the PIN version was not working and while working at the PSK version it I have added some additional functions.
Made a PR once for HA core, but it was refused as it needed to be integrated with the current Bravia PIN component and I don't have enough time to dive into that (neither a good test setup to test the PIN connection besides the PSK connection).
