### ISSUE TITLE
Application source information

### ISSUE THREAD

**Issue by tibehrius** [custom-components/media_player.braviatv_psk#28]
Why are TV channel information displayed, but application information is not?

Here I have the same TV integrated with AndroidTV (ADB), and with Bravia PSK:

https://prnt.sc/ry0ei5
https://prnt.sc/ry0f6y

 The Android integration shows the name of the App and an image of what is currently being displayed. Just do not inform the name of the video title. In the Bravia PSK integration, even the application name does not appear. Is this a mistake, or should it be anyway?

**Comment by gerard33** [comment]
I don’t have a Bravia with Android, so when I developed the component I had no app data to test.

**Comment by gerard33** [comment]
Closing this issue. If there is anyone who can help with adding the app info by making a PR that would really be helpful.
