### ISSUE TITLE
issue with 0.89

### ISSUE THREAD

**Issue by Conarus** [custom-components/media_player.braviatv_psk#3]
Was on 0.85 and everything fine.
Updated to 0.89 and it causes issues as per log;

>     File "/config/custom_components/braviatv_psk/media_player.py", line 7
    <!DOCTYPE html>
    ^
SyntaxError: invalid syntax
Fatal error while loading config: invalid syntax (media_player.py, line 7)
Failed config
  General Errors: 
    - invalid syntax (media_player.py, line 7)

Restore to 0.85 and all fine.

**Comment by Conarus** [comment]
Was on 0.85 and everything fine.
Updated to 0.89 and it causes issues as per log;

>   File "/config/custom_components/braviatv_psk/media_player.py", line 7
    <!DOCTYPE html>
    ^
SyntaxError: invalid syntax
Fatal error while loading config: invalid syntax (media_player.py, line 7)
Failed config
  General Errors: 
    - invalid syntax (media_player.py, line 7)

Restore to 0.85 and all fine.

**Comment by gerard33** [comment]
Well in the Python code there is no `<!DOCTYPE html>` so you didn't copy the py code but the html code.
Get the latest code [here](https://raw.githubusercontent.com/custom-components/media_player.braviatv_psk/master/custom_components/braviatv_psk/media_player.py) and I am sure it will work.

**Comment by Conarus** [comment]
So sorry, complete brain fart.
Please close its working fine.
Thanks for the great work and taking the time to respond.
