### ISSUE TITLE
Invalid response: {'error': [7, 'not power-on'], 'id': 1}

### ISSUE THREAD

**Issue by vlad36N** [custom-components/media_player.braviatv_psk#32]
**Describe the issue**
A clear and concise description of what the issue is.
After update to version: 0.3.3
**Expected behavior**
Have following errors in log:
```
Invalid response: {'error': [7, 'not power-on'], 'id': 1} request path: sony/avContent request params: {"method": "getSourceList", "params": [{"scheme": "tv"}], "id": 1, "version": "1.0"}
Invalid response: {'error': [7, 'not power-on'], 'id': 1} request path: sony/avContent request params: {"method": "getSourceList", "params": [{"scheme": "extInput"}], "id": 1, "version": "1.0"}
```
**Home Assistant version**
Which Home Assistant version are you using. And did it work on a previous version, if so what was the last working version.
Home Assistant 0.109.6
**Screenshots**

**Some extra checks**
Please check the items below
- [x] The correct Pre-Shared Key (PSK) is used in the configuration
- [x] The correct static IP address of the TV is used in the configuration
- [x] The installation instructions for the TV from [here](https://github.com/custom-components/media_player.braviatv_psk#configuration) are followed

**Your config.yaml**
```yaml
media_player:
  - platform: braviatv_psk
    host: 192.168.1.101
    psk: sony
    mac: AA:BB:CC:DD:EE:FF
    sourcefilter:
      - ' HD'
      - HDMI
    name: MyBraviaTV
````

**Output of HA logs**
Paste the relavant output of the HA log here.

Log Details (ERROR)
Logger: braviapsk.sony_bravia_psk
Source: custom_components/braviatv_psk/media_player.py:245
First occurred: 6:50:55 AM (210 occurrences)
Last logged: 7:09:56 AM

    Invalid response: {'error': [7, 'not power-on'], 'id': 1} request path: sony/avContent request params: {"method": "getSourceList", "params": [{"scheme": "tv"}], "id": 1, "version": "1.0"}
    Invalid response: {'error': [7, 'not power-on'], 'id': 1} request path: sony/avContent request params: {"method": "getSourceList", "params": [{"scheme": "extInput"}], "id": 1, "version": "1.0"}

*NOTE: It might take me a while to respond on GitHub (I only maintain this in my free time), but I will respond.*

**Comment by gerard33** [comment]
I see what has caused this. Will make an update asap.

**Comment by vlad36N** [comment]
Thank you

**Comment by gerard33** [comment]
Btw, have you installed `0.3.3` via HACS? For me it was not visible in HACS yet.

**Comment by vlad36N** [comment]
Problems start after update to version: 0.3.3.
![33](https://user-images.githubusercontent.com/30022288/82340981-d931a700-99bd-11ea-99d9-9dd60a18fe43.png)

**Comment by gerard33** [comment]
Yeah I see the relation with 0.3.3 as a change was introduced in one of the PRs which probably has caused this, but I was wondering if that version was available for you in HACS as it didn't show up for me. But based on your screenshot that version is visible for you.

I have made a fix and will release 0.3.4. Please let me know if that fixes it for you.

**Comment by vlad36N** [comment]
Updated to version 0.3.4. So far no entry in a logs.
Thank you

**Comment by vlad36N** [comment]
Gerard, you can close it. 
No entries on logs, about one hour since update to new version 0.3.4.
With version 0.3.3 in one hour 210 occurrences.
Thank you

**Comment by vlad36N** [comment]
Gerard, have one more similar error.
After restarting HA have following in Log:

Logger: braviapsk.sony_bravia_psk
Source: /usr/local/lib/python3.8/site-packages/braviapsk/sony_bravia_psk.py:180
First occurred: 7:07:15 PM (1 occurrences)
Last logged: 7:07:15 PM
Invalid response: {‘error’: [7, ‘not power-on’], ‘id’: 1} request path: sony/system request params: {“method”: “getRemoteControllerInfo”, “params”: [], “id”: 1, “version”: “1.0”}

Same message appear in Log every couple hours.

![](https://community-assets.home-assistant.io/original/3X/c/b/cbd63092a07670ea60fb344eda15b75fd705aa61.png)

![](https://community-assets.home-assistant.io/original/3X/0/4/04063ec079397ec41cf59845301285e5502677fd.png)


![](https://community-assets.home-assistant.io/original/3X/1/e/1e475718218fbae840541b3ebc966aaf007b7394.png)

**Comment by vlad36N** [comment]
Log Details (ERROR)

Logger: braviapsk.sony_bravia_psk
Source: /usr/local/lib/python3.8/site-packages/braviapsk/sony_bravia_psk.py:297
First occurred: August 14, 2020, 10:53:53 PM (1 occurrences)
Last logged: August 14, 2020, 10:53:53 PM
JSON request error:{ "error": [ 7, "not power-on" ], "id": 1 }
