### ISSUE TITLE
Error message

### ISSUE THREAD

**Issue by ramonvanbiljouw** [custom-components/media_player.braviatv_psk#4]
Hi,

I'm getting the following error message:
Invalid response: {'auth_url': {'default': 'http://10.0.1.40:80/sony/webauth/auth_default', 'tv': 'http://127.0.0.1:80/sony/webauth/auth_tv'}, 'error': [403, 'Forbidden'], 'id': 1}
  request path: sony/avContent
  request params: {"method": "getContentList", "params": [{"source": "extInput:composite"}], "id": 1, "version": "1.0"}

I'm on the latest androidtv version, Oreo

Could you help?
Thanks, Ramon

**Comment by gerard33** [comment]
Did you setup a PSK on the TV?
Can you share the relevant part of your config.yaml?

**Comment by ramonvanbiljouw** [comment]
Sure... I have also the original Bravia component installed. Is that possible one of the problems?
Thank for trying to help me. Regards, Ramon

- platform: braviatv_psk
  host: 10.0.1.8
  psk: fakecode
  amp: false
  android: true
  sourcefilter:
    - 'NPO 1 HD'
    - 'NPO 2 HD'
    - 'NPO 3 HD'
    - 'RTL 4 HD'
    - 'RTL 5 HD'
    - 'SBS6 HD'
    - 'RTL 7 HD'
    - 'Veronica HD / Disney XD'
    - 'Net5 HD'
    - 'RTL 8 HD'
    - 'FOX HD'
    - 'RTL Z HD'
    - 'Ziggo TV HD'
    - 'Ziggo Sport HD'
    - 'Comedy Central HD'
    - 'Spike HD'
    - 'Discovery HD'
    - 'National Geographic Channel HD'
    - 'SBS9 HD'
    - 'Eurosport 1 HD'
    - 'TLC HD'
    - 'BBC First HD'
    - 'MTV HD'
    - '24Kitchen HD'
    - HDMI
  name: 4KTV

**Comment by ramonvanbiljouw** [comment]
I think I have found the issue. Placing the psk between '', 'fakecode', solved the problem for now at least. I'll keep you posted. Regards, Ramon

**Comment by ericliu1234567** [comment]
Hi,

I'm getting some problem of my Bravia, everything control are good, but just can't trun on TV on HA.
however when I turn on TV by remote control directly, HA also can syn the TV status。
Unfortunately, log report didn't have about related Bravia issue.

my Bravia model are KD-65X9000E with latest version

  - platform: braviatv_psk
    host: 192.168.0.176
    psk: sony
    mac: d8:0f:99:66:35:0b
    amp: True
    name: sony_bravia_tv

Could you help? 
Thanks, Ramon

**Comment by ericliu1234567** [comment]
Hi,

I'm getting some problem of my Bravia, everything control are good, but just can't trun on TV on HA.
however, when I turn on TV by remote control directly, HA also can syn the TV status。
Unfortunately, log report didn't have about related Bravia issue.

my Bravia model are KD-65X9000E with latest version.

platform: braviatv_psk
host: 192.168.0.176
psk: sony
mac: d8:0f:99:66:35:aa
amp: True
name: sony_bravia_tv

Could you help?
Thanks, Ramon

**Comment by gerard33** [comment]
@ericliu1234567 guess you have an Android TV? Then you need to set `Android: True` in the config.

**Comment by ericliu1234567** [comment]
> Hi,
> 
> I'm getting some problem of my Bravia, everything control are good, but just can't trun on TV on HA.
> however, when I turn on TV by remote control directly, HA also can syn the TV status。
> Unfortunately, log report didn't have about related Bravia issue.
> 
> my Bravia model are KD-65X9000E with latest version.
> 
> platform: braviatv_psk
> host: 192.168.0.176
> psk: sony
> mac: d8:0f:99:66
> amp: True
> name: sony_bravia_tv
> 
> Could you help?
> Thanks, Ramon

problem solved, thanks!!

**Comment by gerard33** [comment]
@ramonvanbiljouw My guess is that your PSK starts with a `0`. Is that correct? That is probably the reason it needs to be between quotes in your case. Will update the readme if needed.

Everything else is working now?

**Comment by ramonvanbiljouw** [comment]
Hi Gerard, you are exactly right; the psk starts with a zero. Everything is working great now. I would of like to have the knowledge to extend the code to add more commands besides the 20 something you have programmed. Is it that easy to just add the command like Num1 as you did. For example: AudioOutput_AudioSystem. It would be kind if you answer that, but I understand that could be the beginning of an endless FAQ. 😉 thanks for helping me. And yes, it would be useful to add the remark regarding the zero. Have a good one, Ramon.

**Comment by ramonvanbiljouw** [comment]
Apparently it is that simple. You can add commands 👍
