### ISSUE TITLE
Add Kodi shortcut

### ISSUE THREAD

**Issue by rukakolink** [custom-components/media_player.braviatv_psk#41]
Hi,

i found this command to open kodi 
curl -H “Content-Type: application/json” -H “X-Auth-PSK: sony” -X POST http://192.168.1.143/DIAL/apps/com.sony.dtv.org.xbmc.kodi.org.xbmc.kodi.Splash

but how can i add it?

and i run this curl -H “Content-Type: application/json” -H “X-Auth-PSK:sony” -X POST -d ‘{“id”: 1, “method”: “getApplicationList”, “version”: “1.0”, “params”: [""]}’ http://192.168.1.143/sony/appControl
 but it gives error can you help?

thanks

**Comment by gerard33** [comment]
Have you checked the documentation -> https://github.com/custom-components/media_player.braviatv_psk#braviatv_pskbravia_open_app?

You can use the service `braviatv_psk.bravia_open_app` and use uri `com.sony.dtv.org.xbmc.kodi.org.xbmc.kodi.Splash`.

**Comment by rukakolink** [comment]
Yes i have but there any way to add on the remote like Netflix?

**Comment by gerard33** [comment]
The remote?
You can add a service to a button in HA if that is what you mean. If you clearify what you want we can help you better.

**Comment by gerard33** [comment]
Closing this issue.
