### ISSUE TITLE
Can't turn on TV

### ISSUE THREAD

**Issue by ericliu1234567** [custom-components/media_player.braviatv_psk#5]
Hi,

I'm getting some problem of my Bravia, everything control are good, but just can't turn on TV on HA.
When I turn on TV by remote control directly, HA also can syn the TV status。
Unfortunately, log report didn't have about related Bravia issue.

my Bravia model are KD-65X9000E with latest version.

platform: braviatv_psk
host: 192.168.0.176
psk: sony
mac: d8:0f:99:66:35:aa
amp: True
name: sony_bravia_tv

Could you help?
Thanks, Ramon

**Comment by gerard33** [comment]
Duplicate, solved [here](https://github.com/custom-components/media_player.braviatv_psk/issues/4#issuecomment-480152127).
