### ISSUE TITLE
Some issues on android tv

### ISSUE THREAD

**Issue by Drafteed** [custom-components/media_player.braviatv_psk#51]
**Describe the issue**

- media_next_track, media_previous_track does, media_pause not work in android tv apps.
- current volume show as NaN
- title is always `TV_NO_INFO`, instead `TV_APP_OPENED` in any android app 

**Expected behavior**

Hello @gerard33! Thx for nice work!

Sony KD-XF7596. Android TV 9.0.

Some issues:

**1. Media Next/Prev Track does not work**

**media_next_track**, **media_previous_track** trying to change the channel, not the track in any android tv apps (YouTube, ViMu Player, VLC...). media_pause also does not work.

I think there is a mistake in places like this:

https://github.com/custom-components/media_player.braviatv_psk/blob/5217bf1937d3ec8cae9f56704ad45a81613a5c2c/custom_components/braviatv_psk/media_player.py#L597-L607

`self._program_name` in current case = `TV_NO_INFO`, not `None`. Therefore after check method trigger ChannelUp.

**2. Current volume show as NaN**

I'm not sure, but i guess it appeared after updating to AndroidTV 9.0.

**3.  Media title is always shows `TV_NO_INFO`**

Media title is always shows `TV_NO_INFO` in any android app, instead  `TV_APP_OPENED`, such as [official integration.](https://www.home-assistant.io/integrations/braviatv/)

**Bravia custom component version**
latest: v0.4.0

**Home Assistant version**
latest: 2021.4.1, Container

**Screenshots**

![chrome_2021-04-09_18-55-50](https://user-images.githubusercontent.com/11841379/114207627-3f704100-9965-11eb-9555-ba373b6adf0b.png)

![chrome_2021-04-09_18-56-30](https://user-images.githubusercontent.com/11841379/114207690-51ea7a80-9965-11eb-8f77-c645b2a7ed0c.png)

**Some extra checks**
Please check the items below
- [x] The correct Pre-Shared Key (PSK) is used in the configuration
- [x] The correct static IP address of the TV is used in the configuration
- [x] The installation instructions for the TV from [here](https://github.com/custom-components/media_player.braviatv_psk#installation-instructions-tv) are followed

**Your config.yaml**
```yaml
- platform: braviatv_psk
  name: "Sony TV (psk)"
  host: 192.168.1.20
  psk: sony
  android: true
````

**Output of HA logs**
Paste the relavant output of the HA log here.

*NOTE: It might take me a while to respond on GitHub (I only maintain this in my free time), but I will respond.*

**Comment by Drafteed** [comment]
Regards `NaN` volume - it happens when headphone connected to TV. 

API returns:

```json
{
    "result": [
        [
            {
                "target": "headphone",
                "volume": 7,
                "mute": false,
                "maxVolume": 100,
                "minVolume": 0
            }
        ]
    ],
    "id": 1
}
```

**Comment by gerard33** [comment]
Will have a look at the volume issue.

For the other issues I can't really help as I don't have an Android TV and can't do the proper development.

**Comment by rchl** [comment]
> **media_next_track**, **media_previous_track** trying to change the channel, not the track in any android tv apps (YouTube, ViMu Player, VLC...). media_pause also does not work.

As your screenshot shows, the next and previous track buttons are not even available for that entity. That means that they can't be called in the first place, which looks like the main issue here.

As far as I've tested, those are only available when the component is in `STATE_PLAYING` state. Currently the component is only ever in state `STATE_ON` or `STATE_OFF`.

After forcing `STATE_PLAYING` instead of `STATE_ON` those buttons become available but don't work due to that issue that you've mentioned with some variables being different than expected. I get:
`program_media_type: None, program_name: "No info (resumed after pause or app opened)"`

So there is a couple of issues that need to be fixed.

But I'm not sure if TV gives enough information to know whether app or something else is opened.

**Comment by rchl** [comment]
When an app like YouTube is open, this is what is returned when getting playing info:

```
curl -i -X POST \
   -H "Content-Type:application/json" \
   -H "X-Auth-PSK:sony" \
   -d \
'{
  "id": 1,
  "method": "getPlayingContentInfo",
  "version": "1.0",
  "params": []
}' \
 'http://192.168.2.5/sony/avContent?'
HTTP/1.1 200 OK
Content-Type: application/json
Content-Length: 36
Connection: keep-alive

{"error":[7,"Illegal State"],"id":1}
```

**Comment by gerard33** [comment]
Note to self; see this PR on HA for a fix in the current implementation which forces speakers only. Check if that will solve the headphones issue as mentioned in this issue.

**Comment by MatthewZMD** [comment]
Any updates on the headphones issue?

**Comment by MatthewZMD** [comment]
I don't know if it's related, but everytime when I turn on the Bravia TV, I'm seeing this error in the log:
```
2021-07-06 17:41:12 ERROR (SyncWorker_4) [braviapsk.sony_bravia_psk] Invalid response: {'error': [3, 'Illegal Argument'], 'id': 1}
  request path: sony/avContent
  request params: {"method": "getSourceList", "params": [{"scheme": "tv"}], "id": 1, "version": "1.0"}

```

**Comment by Drafteed** [comment]
Use [core HA Bravia TV](https://www.home-assistant.io/integrations/braviatv/) integration. Issue with headphones fixed in [#50726](https://github.com/home-assistant/core/pull/50726). I also [added remote platform](https://github.com/home-assistant/core/pull/50845), which will be added in next release (tomorrow).

Core integration also supports PSK auth.

**Comment by MatthewZMD** [comment]
I actually tried that before finding this. It prompted me for a PIN when I tried to integrate, I have no idea what that PIN means or where to find that. :(

**Comment by Drafteed** [comment]
@MatthewZMD enter the PSK code that you used with this integration instead of pin.

**Comment by MatthewZMD** [comment]
@Drafteed It doesn't work with `Failed to connect` message.

**Comment by Drafteed** [comment]
@MatthewZMD double check IP and pre-shared-key. You can also follow **TV DOES NOT GENERATE NEW PIN** section in [official doc](https://www.home-assistant.io/integrations/braviatv/).

**Comment by MatthewZMD** [comment]
Yep, I checked, it didn't work. I eventually gave up and configured Android TV. It is a pain in its own way, but it worked.

**Comment by Drafteed** [comment]
@MatthewZMD whitch TV model?

**Comment by rchl** [comment]
@Drafteed if, as you are saying, the official integration supports the PSK method then why its UI only mentions PIN?

![Screenshot 2021-08-23 at 08 51 07](https://user-images.githubusercontent.com/153197/130403279-940f7708-1d95-4720-929f-ec1f6ba665f7.png)

Also, the TV doesn't need to be ON to set it up using the PSK method.
In any case, I've tried that on my TV (with TV off) and it didn't work to use the PSK code (`sony` by default).

**Comment by Drafteed** [comment]
@rchl @MatthewZMD Probably the longest answer, but core integration has [official support PSK auth](https://www.home-assistant.io/integrations/braviatv/#authentication) in latest releases.
