### ISSUE TITLE
Is this component still needed

### ISSUE THREAD

**Issue by rchl** [custom-components/media_player.braviatv_psk#59]
It seems like the official bravia integration has caught up with most of the features.

It can send arbitrary commands using the `remote` service.
It exposes all installed apps in the "sources" list of the entity.

It doesn't seem to support connecting using PSK yet but I wonder now what's the benefit of that over the PIN method? Functionality wise, I don't see any difference.

**Comment by rchl** [comment]
Well, I also started using your integration for some reason but I don't remember what was the reason now.

Ideally, we would try to use the official integration now rather than maintaining a parallel solution. Since the official one has been actively maintained, it would be possible to improve it and add features there now.

Those thoughts came to me after working on rebasing the #42 PR and realizing that:
 - the official integration already implements some of that stuff (the UI flow for example)
 - that the PR has unsolved issues that would require more work.

I'd probably rather put the effort in adding PSK method to the official integration than fixing the issues in the PR.

**Comment by gerard33** [comment]
> I'd probably rather put the effort in adding PSK method to the official integration than fixing the issues in the PR.

I fully agree with that. For me there is no need to make to big changes to this custom component as the official integration has made big steps lately. Besides that this custom component is working fine as is.
