### ISSUE TITLE
Support for older models

### ISSUE THREAD

**Issue by lcavalli** [custom-components/media_player.braviatv_psk#61]
I own an old BRAVIA model (KDL-40EX521, 2012 I think) and the IRCC interface is exposed on `http://<ip>/IRCC`, instead of `http://<ip>/sony/IRCC.` Furthermore my BRAVIA doesn't need the PSK (but a fake X-Auth-PSK: 0000 header doesn't hurt).

Is it possible to have a flag in the integration configuration to force the old URL without the "/sony/" part? I think that this addition will add support to my and many other old models. Thank you.

**Comment by gerard33** [comment]
I have had an older Bravia model and the API support was very limited, so it seems to be that the other url will not be the only part that needs to be changed.
Have you had a look at https://www.home-assistant.io/integrations/braviatv/#for-tvs-older-than-2013?

**Comment by lcavalli** [comment]
I think that using CEC client provides a very limited set of functionalities to control the TV (on and off). On the other side I have this app https://play.google.com/store/apps/details?id=tv.remote.control.sonytv on my mobile phone and I have a perfect replica of my TV remote that provides full control. I can can select input source, change TV channel, turn TV off, enter TV menu, whatever I can do with the remote. I sniffed the data stream between the app and the TV and it uses the IRCC protocol to send the simulated button pressures.

**Comment by gerard33** [comment]
Allright let's give it a try 😄
I have change the url in the lib from `/sony/IRCC` to `/IRCC` and made a beta release.
Can you test it by changing `requirements` in manifest.json from
`pySonyBraviaPSK==0.2.3` to `pySonyBraviaPSK==0.2.4b0`?

**Comment by mitch55500** [comment]
Hi, 

I have a similar model (40EX720) and works with [](https://play.google.com/store/apps/details?id=tv.remote.control.sonytv) on my mobile phone. 
In manifest.json, I have changed pySonyBraviaPSK==0.2.3 to pySonyBraviaPSK==0.2.4b0.

I try to integrate my TV, I enter the IP of my TV but no code PSK appears on my TV.

What's wrong?
@lcavalli , is it working for you?

**Comment by lcavalli** [comment]
Hi,
tried the beta version of the Bravia PSK library and although I'm confident it could work with the legacy IRCC endpoint on the TV, unfortunately the integration is blocked by the preliminary configuration steps done via the bravia_req_json calls (get TV power status, volume status, etc etc...).
Maybe the best solution here is not to touch the current library and try to develop a legacy integration, alongside with a minimal IRCC library.

**Comment by gerard33** [comment]
That's a pity it doesn't work. Feel free to fork this repo and try if you get it to work.
Closing this issue.
