### ISSUE TITLE
Error in HA Logs

### ISSUE THREAD

**Issue by jamespreedy** [custom-components/media_player.braviatv_psk#66]
**Describe the issue**
Hiya, I'm getting the below error in my logs a few times a day.

```
2022-01-29 22:22:55 ERROR (SyncWorker_2) [braviapsk.sony_bravia_psk] Invalid response: {'error': [7, 'not power-on'], 'id': 1}
request path: sony/avContent
request params: {"method": "getContentList", "params": [{"source": "tv:dvbc", "stIdx": 0}], "id": 1, "version": "1.0"}
```
**Expected behavior**
I'm unsure if its causing anything to not function correctly - I simply wanted to report the issue.

**Bravia custom component version**
v0.41

**Home Assistant version**
v2021.12.10

**Screenshots**
n/a

**Some extra checks**
Please check the items below
- [✅] The correct Pre-Shared Key (PSK) is used in the configuration
- [✅] The correct static IP address of the TV is used in the configuration
- [✅] The installation instructions for the TV from [here](https://github.com/custom-components/media_player.braviatv_psk#installation-instructions-tv) are followed

**Your config.yaml**
```yaml
- platform: braviatv_psk
  host: 192.168.1.104
  psk: sony
  mac: $$$$$
  amp: False
  android: False
  sourcefilter: 
    - Sky Q
  time_format: 12H
  user_labels: True
  name: Bedroom 4 TV
```

**Output of HA logs**
```
2022-01-29 22:22:55 ERROR (SyncWorker_2) [braviapsk.sony_bravia_psk] Invalid response: {'error': [7, 'not power-on'], 'id': 1}
request path: sony/avContent
request params: {"method": "getContentList", "params": [{"source": "tv:dvbc", "stIdx": 0}], "id": 1, "version": "1.0"}

```

Thanks for your help in advance, please let me know if there's any additional information I can get for you. 🍺
*NOTE: It might take me a while to respond on GitHub (I only maintain this in my free time), but I will respond.*

**Comment by gerard33** [comment]
That message is there when there is no connection to the TV. Should only happen when TV is just started or shut down.

**Comment by jamespreedy** [comment]
Ah ok, I didn't realise it was expected.
Thanks for your help!

**Comment by gerard33** [comment]
It's a message that the library returns to the integration. Maybe warning suits this better than error, but nothing wrong. Closing the issue.
