### ISSUE TITLE
Picture in Picture

### ISSUE THREAD

**Issue by datdamnzotz** [custom-components/media_player.braviatv_psk#67]
**Is your feature request related to a problem? Please describe.**
Just got this all setup (everything else is awesome!) and was wondering does this module support any Picture in Picture functionality?

**Describe the solution you'd like**
Home assistant detects motion on  a camera - Plops it in Picture in Picture on the TV.

**Describe alternatives you've considered**
Dug and dug and haven't found a solution to activate Picture in Picture.  Maybe I am missing it someplace?

**Comment by gerard33** [comment]
PiP is not supported, but if you have an Android TV you can use this to show a camera picture -> https://www.home-assistant.io/integrations/nfandroidtv.

**Comment by datdamnzotz** [comment]
Thanks @gerard33, I did see that one, I was looking to activate a live stream in the PIP.  I really didn't want to dig into the android API to see if it was possible.
https://pro-bravia.sony.net/develop/integrate/rest-api/spec/index.html
I guess one could toss an app up on the TV and activate it that way.
https://pro-bravia.sony.net/develop/app/getting-started/index.html

Tho after some digging this might work.
https://github.com/rogro82/PiPup

**Comment by gerard33** [comment]
The PiPup looks great, but I see it's not being updated lately.
You can also use the new play media action from HA 2022.3 but that's full screen and not PiP.
Closing this issue, feel free to re-open if you have any other questions or updates.
