### ISSUE TITLE
manifets.json file is needed under HA 0.92b1

### ISSUE THREAD

**Issue by bieniu** [custom-components/media_player.braviatv_psk#7]
With braviatv_psk component HA 0.92b1 don't start. manifet.json file is needed. I added a file with this content and HA starts and the component works.
```
{
  "domain": "braviatv_psk",
  "name": "Bravia TV PSK",
  "requirements": [
    "pySonyBraviaPSK==0.1.7"
  ],
  "dependencies": [
    "configurator"
  ]
}
```

**Comment by gerard33** [comment]
Thanks, will add this file to the repository.
Did you also remove the requirements from the py file?

**Comment by bieniu** [comment]
This issue was premature. On HA 0.92b2, the manifest.json file isn't necessary.
