### ISSUE TITLE
Error loading the component.

### ISSUE THREAD

**Issue by MYKSelf** [custom-components/media_player.braviatv_psk#8]
After 0.92 release, the component didn't load on Home Assistant. The component shows this error:

`Integration braviatv_psk not found when trying to verify its media_player platform.`

After taking a look, it seems that now is mandatory to create a `__init__.py` file, even if it's an stub, for Home Assistant to load the component.

I've created an `__init__.py` file on the same folder as the `media_player.py` file, with this content:

```
"""bravia_psk stub file"""
```

And after rebooting home assistant and reload the GUI, the component shows and works again.

But this obviously is an inelegant solution. Please, can you take a look for a better solution?

New requirements are listed on

`https://developers.home-assistant.io/docs/en/creating_integration_file_structure.html`

and

`https://developers.home-assistant.io/docs/en/creating_integration_manifest.html`

Thanks to @cogneato on Discord for the help troubleshooting this.

**Comment by Snake1980** [comment]
Yesterday I updated to homeassistant 0.92.
I used this component today for the first time.
No errors or warning (always present for custom components) in homeassistant-log...my Sony XF9005 is not present on HA.
I think (as MYKSelf) this component is not loaded
 
@MYKSelf I've created `__init__.py` file but it doesn't work.
This is my log with your temp solution:

`2019-04-25 17:36:01 ERROR (MainThread) [homeassistant.components.media_player] Error while setting up platform braviatv_psk
Traceback (most recent call last):
  File "/srv/homeassistant/lib/python3.5/site-packages/homeassistant/helpers/entity_platform.py", line 126, in _async_setup_platform
    SLOW_SETUP_MAX_WAIT, loop=hass.loop)
  File "/usr/lib/python3.5/asyncio/tasks.py", line 400, in wait_for
    return fut.result()
  File "/usr/lib/python3.5/asyncio/futures.py", line 293, in result
    raise self._exception
  File "/usr/lib/python3.5/concurrent/futures/thread.py", line 55, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/homeassistant/.homeassistant/custom_components/braviatv_psk/media_player.py", line 89, in setup_platform
    [BraviaTVDevice(host, psk, mac, name, amp, android, source_filter)])
  File "/home/homeassistant/.homeassistant/custom_components/braviatv_psk/media_player.py", line 98, in __init__
    from braviapsk import sony_bravia_psk
ImportError: No module named 'braviapsk'`

**Comment by MYKSelf** [comment]
Hmmmm... the module is named "bravia_psk". Take a look at the configuration.yaml, cause I think you've missed a "_" somewhere... :)

**Comment by Snake1980** [comment]
Checked...but I think it's ok...

**configuration.yaml**
`- platform: braviatv_psk
  host: 192.168.1.26
  psk: <my_psk>
  mac: <my_mac_address>
  amp: False
  android: True
  sourcefilter:
    - ' HD'
    - HDMI
  name: SonyXF90`

**custom component**
`pi@snakeberry:/home/homeassistant/.homeassistant/custom_components/braviatv_psk $ ls -alrt
total 32
drwxr-xr-x 5 homeassistant homeassistant  4096 Apr 25 18:57 ..
-rw-r--r-- 1 homeassistant homeassistant 13895 Apr 25 18:57 media_player.py
-rw-r--r-- 1 homeassistant homeassistant    27 Apr 25 19:00 __init__.py
drwxr-xr-x 3 homeassistant homeassistant  4096 Apr 25 19:00 .
drwxr-xr-x 2 homeassistant homeassistant  4096 Apr 25 19:00 __pycache__
pi@snakeberry:/home/homeassistant/.homeassistant/custom_components/braviatv_psk `

The error is on media_player.py at line 98...
`from braviapsk import sony_bravia_psk`

**Comment by gerard33** [comment]
Just restart HA and this should be fixed.

Have seen this issue before and it was solved by a restart. Guess the pypi library is not installed conpletely when the component wants to use it.

**Comment by gerard33** [comment]
@MYKSelf will have a look at that once I have upgraded to 0.92.

But if the `__init__.py` is needed for custom components then that’s the actual solution to use.

**Comment by MYKSelf** [comment]
@gerard33 , I think a `manifest.json` file is (or at least will be in the near future) mandatory too. It must be on the same folder as the component. This will prevent problems as the required dependencies will be downloaded and installed before starting the component (in fact, I think that was the problem with @Snake1980 ). I think the one needed for your component will be in the line of this:

```
{
  "domain": "braviatv_psk",
  "name": "Bravia TV with PSK",
  "documentation": "https://github.com/custom-components/media_player.braviatv_psk",
  "dependencies": [],
  "codeowners": ["@gerard33"],
  "requirements": ["pySonyBraviaPSK==0.1.7"]
}
```

I've composed this after taking a quick look at your code. Of course, I'm sure you can construct a more complete version of this file :)

Thanks for the gook work, @gerard33 :)

**Comment by Snake1980** [comment]
Adding __init__.py and manifest.json it works.

**Comment by gerard33** [comment]
The `manifest.json` is not needed according to balloob on Discord and on a blog post.
See this post for links to the Discord posts https://community.home-assistant.io/t/life360-device-tracker-platform/52406/784?u=gerard33.

And the link to the blog post https://developers.home-assistant.io/blog/2019/04/12/new-integration-structure.html

> Home Assistant 0.92 introduces a new manifest.json for integrations. This file, **which is optional for custom components**, is used by integrations to specify metadata: name, link to the documentation, dependencies, requirements and code owners. We are exploring leveraging manifest.json for additional future features, like tracking breaking changes or allowing custom components to provide config flows and being discovered.

Will check this when I update to 0.92.

**Comment by gerard33** [comment]
Just updated to 0.92 and it works with only the `__init__.py` file. I have added that file on Github as well.

So it will work without `manifest.json` and the issue that @Snake1980 had was the same issue as I have seen earlier, the pypi package was still installing when HA tried to call the library. That is solved after a restart.

**Comment by Snake1980** [comment]
Thank you @MYKSelf and thank you @gerard33.
I deleted `manifest.json` and restarted HA just adding only `__init__.py`
It works!

**Comment by MYKSelf** [comment]
Great. Thanks for everything, @gerard33.
